#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════
   TUVP build script — emits per-article stub HTML files.

   Why this exists:
     The site is a single-page app with client-side routing. When a bot
     (WhatsApp / X / iMessage / etc.) fetches an article URL like
       https://tuvp.in/article/group-a-2026-fifa-wc
     it doesn't run JavaScript. So whatever HTML the server returns at
     that URL is the only thing the bot sees when generating a link
     preview. This script generates a static HTML stub per article with
     the right Open Graph / Twitter Card meta tags baked in, so shares
     render properly.

   What it does:
     For every article in articles.js, copies index.html into
     article/<id>/index.html, swapping the <!-- BUILD:OG_START --> …
     <!-- BUILD:OG_END --> block with per-article OG meta tags.

   When to run it:
     - After adding/editing an article in articles.js
     - After editing index.html (anything that affects the SPA shell)

   How to run it:
     node build.js
═══════════════════════════════════════════════════════════════════ */

const fs   = require('fs');
const path = require('path');

const SITE_ORIGIN = 'https://tuvp.in';

const { ARTICLES } = require('./articles.js');
const indexHtml = fs.readFileSync('index.html', 'utf8');

// Sanity check: confirm the sentinel comments are present.
const OG_RE = /<!-- BUILD:OG_START[\s\S]*?BUILD:OG_END -->/;
if (!OG_RE.test(indexHtml)) {
  console.error('ERROR: index.html is missing <!-- BUILD:OG_START --> / <!-- BUILD:OG_END --> sentinels.');
  process.exit(1);
}

// Strip body_html down to plain text for a usable og:description.
// Removes <br>, headings, paragraphs, etc., collapses whitespace,
// and truncates at ~200 chars on a word boundary.
function plainTextFromBody(html, maxLen = 200) {
  const text = html
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<\/?(p|h1|h2|h3|h4|h5|h6|blockquote|article|div|strong|em|span)[^>]*>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&middot;/g, '·')
    .replace(/\s+/g, ' ')
    .trim();
  if (text.length <= maxLen) return text;
  const cut = text.slice(0, maxLen);
  const lastSpace = cut.lastIndexOf(' ');
  return (lastSpace > maxLen * 0.6 ? cut.slice(0, lastSpace) : cut) + '…';
}

// Escape for safe inclusion in an HTML attribute value.
function attr(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function buildOgBlock(a) {
  const url   = `${SITE_ORIGIN}/article/${a.id}`;
  const desc  = a.subtitle?.trim() || plainTextFromBody(a.body_html || '');
  const image = a.image_url ? `${SITE_ORIGIN}/${a.image_url}` : `${SITE_ORIGIN}/uvp_logo.png`;
  return `<!-- BUILD:OG_START — generated by build.js for article ${a.id} -->
<meta name="description" content="${attr(desc)}">
<meta property="og:site_name" content="The Unmaiyana Vetti People">
<meta property="og:type" content="article">
<meta property="og:title" content="${attr(a.title)}">
<meta property="og:description" content="${attr(desc)}">
<meta property="og:image" content="${attr(image)}">
<meta property="og:url" content="${attr(url)}">
<meta property="article:published_time" content="${attr(a.date || '')}">
<meta property="article:author" content="${attr(a.author || '')}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${attr(a.title)}">
<meta name="twitter:description" content="${attr(desc)}">
<meta name="twitter:image" content="${attr(image)}">
<!-- BUILD:OG_END -->`;
}

let written = 0;
for (const a of ARTICLES) {
  const stub = indexHtml.replace(OG_RE, buildOgBlock(a));
  const outDir  = path.join('article', a.id);
  const outFile = path.join(outDir, 'index.html');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outFile, stub);
  written++;
  console.log(`  wrote ${outFile}`);
}

console.log(`\nbuilt ${written} article stub${written === 1 ? '' : 's'}.`);

// Also keep 404.html in sync with index.html (it's the catch-all SPA fallback).
fs.writeFileSync('404.html', indexHtml);
console.log('synced 404.html ← index.html');
